### ISSUE TITLE
Method for downloading pack file when dir indexes are enabled

### ISSUE THREAD

**Issue by strawp** [evilpacket/DVCS-Pillage#13]
Didn't know about this project until now but I wrote a similar one a couple of years ago. It can automatically grab the pack file for projects if dir listings is enabled, which is more likely to get you all the source code.

https://github.com/strawp/greedy-git/blob/master/greedy-git#L396

I also do a couple of things in the output report to identify middleware etc. Feel free to use any ideas.

**Comment by evilpacket** [comment]
Thanks for pointing this out. If dir listing is enabled you can just use wget / git to clone it 100%. This tool was more designed when that condition didn't exist.
